[features]
seeds = false
skip-lint = false
[programs.localnet]
sol_swap = "76CiXu6jUeP4H9irUKj7Xv2CrzdcnaSP8iysX27Vrpqo"
[programs.devnet]
sol_swap = "76CiXu6jUeP4H9irUKj7Xv2CrzdcnaSP8iysX27Vrpqo"
[programs.testnet]
sol_swap = "76CiXu6jUeP4H9irUKj7Xv2CrzdcnaSP8iysX27Vrpqo"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "testnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
