[features]
seeds = false
skip-lint = false
[programs.localnet]
sol_swap = "8LRf1eAHEYiEStG1qGSdkFTDMpvhP6FZEBiSoDGLzYVk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
