[features]
seeds = false
skip-lint = false
[programs.localnet]
sol_swap = "DJ7sVUp3VnB56PHiKkX8LTM8pUw8ghQ2yziQFbu2mygn"
[programs.devnet]
sol_swap = "DJ7sVUp3VnB56PHiKkX8LTM8pUw8ghQ2yziQFbu2mygn"
[programs.testnet]
sol_swap = "DJ7sVUp3VnB56PHiKkX8LTM8pUw8ghQ2yziQFbu2mygn"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/mac/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
